Fix version check test
gpuopenanalytics/pynvml pull request #23
Opened 2020-01-07 09:39 UTC by ksangeek

1. Proposed fix for https://github.com/gpuopenanalytics/pynvml/issues/22 where I have removed the typecast of the version to `float`, as that does not work with driver versions like `440.33.01` or `418.87.00`. I have modified the version check test case to check if the major version number is greater than 0. Please let me know if there are suggestions to improve the test. 
2. I have also modified the `test_nvmlSystemGetNVMLVersion` to test the API `nvmlSystemGetNVMLVersion()` instead of `nvmlSystemGetDriverVersion()`, which I think it was intended to. Else `test_nvmlSystemGetNVMLVersion()` and `test_nvmlSystemGetDriverVersion()` were testing the same API.

2020-01-07 09:46 UTC, ksangeek commented
Unit test results -

```python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:18:58)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynvml
>>> pynvml.nvmlInit()
>>> pynvml.nvmlSystemGetDriverVersion().decode()
'440.33.01'
>>> vsn = pynvml.nvmlSystemGetDriverVersion().decode()
>>> print('[Driver Version: '+vsn+']', end =' ')
[Driver Version: 440.33.01] >>>
>>> int(vsn.split('.')[0])
440
>>> int(vsn.split('.')[0]) > 0.0
True


>>> vsn = pynvml.nvmlSystemGetNVMLVersion().decode()
>>> print('[NVML Version: '+vsn+']', end =' ')
[NVML Version: 10.440.33.01] >>>
>>> int(vsn.split('.')[0])
10
>>> int(vsn.split('.')[0]) > 0.0
True
```

2020-01-07 17:02 UTC, rjzamora requested changes
Thanks for pointing out the problem @ksangeek!  Perhaps we should just use `LooseVersion` for this.  You can just add `from distutils.version import LooseVersion` to the file header (then use the suggested assert statements)

2020-01-07 17:02 UTC, rjzamora commented on pynvml/tests/test_nvml.py
> +    assert int(vsn.split('.')[0]) > 0.0
Instead of this `split` statement, use: `assert vsn > LooseVersion("0.0")`

2020-01-07 17:02 UTC, rjzamora commented on pynvml/tests/test_nvml.py
> +    assert int(vsn.split('.')[0]) > 0.0 # Developing with 396.44
Same here

2020-01-08 10:02 UTC, ksangeek commented on pynvml/tests/test_nvml.py
> +    assert int(vsn.split('.')[0]) > 0.0
I had read about `LooseVersion()` but was not sure on how to use it here. Thanks for the suggestion, will make this change.

2020-01-08 14:44 UTC, rjzamora approved these changes

2020-01-08 14:46 UTC, rjzamora commented
LGTM - Thanks @ksangeek !

2020-01-08 14:46 UTC, merged